FROM node:20.12.2

RUN apt-get update && apt-get install -y make && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Копируем зависимости для лучшего кэширования
COPY app/package.json app/package-lock.json ./
RUN npm ci

COPY app/. .

EXPOSE 8080
ENV NODE_ENV=production

RUN make build

CMD ["make", "start"]